branches:
  only:
    - master

sudo: false
language: node_js
node_js: '8'
dist: trusty
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

matrix:
  include:
    - script:
      - yarn dist
      - yarn test
      - yarn codecov

    - language: objective-c
      osx_image: xcode9.2
      script: .travis/deploy.sh
      after_success:
        - npm install -g @zeus-ci/cli
        - zeus upload -t "application/tar+npm" *.tgz
      after_failure:
        - npm install -g @zeus-ci/cli
        - zeus upload -t "application/tar+npm" *.tgz
